// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQozJVsqZMdXQXSdnm5e6bJS4yYAKcohU',
    appId: '1:818759700583:web:b9e6d6775e089b8624c4c2',
    messagingSenderId: '818759700583',
    projectId: 'delicious-food-b9f62',
    authDomain: 'delicious-food-b9f62.firebaseapp.com',
    storageBucket: 'delicious-food-b9f62.firebasestorage.app',
    measurementId: 'G-C41XZPJW0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC99X7oX4QF1tER3waGua_y4F68ob4W3A4',
    appId: '1:818759700583:android:6fbc00b24dcae85024c4c2',
    messagingSenderId: '818759700583',
    projectId: 'delicious-food-b9f62',
    storageBucket: 'delicious-food-b9f62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0RMCRHntBjBMDo9bxdqanEOZuMc2oYrQ',
    appId: '1:818759700583:ios:1412af40e262624c24c4c2',
    messagingSenderId: '818759700583',
    projectId: 'delicious-food-b9f62',
    storageBucket: 'delicious-food-b9f62.firebasestorage.app',
    iosBundleId: 'com.example.deliciousFood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0RMCRHntBjBMDo9bxdqanEOZuMc2oYrQ',
    appId: '1:818759700583:ios:1412af40e262624c24c4c2',
    messagingSenderId: '818759700583',
    projectId: 'delicious-food-b9f62',
    storageBucket: 'delicious-food-b9f62.firebasestorage.app',
    iosBundleId: 'com.example.deliciousFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQozJVsqZMdXQXSdnm5e6bJS4yYAKcohU',
    appId: '1:818759700583:web:93fb9f3a6d305c0024c4c2',
    messagingSenderId: '818759700583',
    projectId: 'delicious-food-b9f62',
    authDomain: 'delicious-food-b9f62.firebaseapp.com',
    storageBucket: 'delicious-food-b9f62.firebasestorage.app',
    measurementId: 'G-7W5PQ2JPS0',
  );
}
